<!--
var log = [];
try {
    if (FileException.NOT_FOUND_ERR != 1)
        log.push('FileException.NOT_FOUND_ERR was not 1');
    if (FileException.SECURITY_ERR != 2)
        log.push('FileException.SECURITY_ERR was not 2');
    if (FileException.ABORT_ERR != 3)
        log.push('FileException.ABORT_ERR was not 3');
    if (FileException.NOT_READABLE_ERR != 4)
        log.push('FileException.NOT_READABLE_ERR was not 4');
    if (FileException.ENCODING_ERR != 5)
        log.push('FileException.ENCODING_ERR was not 5');
    if ('code' in FileException)
        log.push('FileException.code existed');
    if (FileException.prototype.NOT_FOUND_ERR != 1)
        log.push('FileException.prototype.NOT_FOUND_ERR was not 1');
    if (FileException.prototype.SECURITY_ERR != 2)
        log.push('FileException.prototype.SECURITY_ERR was not 2');
    if (FileException.prototype.ABORT_ERR != 3)
        log.push('FileException.prototype.ABORT_ERR was not 3');
    if (FileException.prototype.NOT_READABLE_ERR != 4)
        log.push('FileException.prototype.NOT_READABLE_ERR was not 4');
    if (FileException.prototype.ENCODING_ERR != 5)
        log.push('FileException.prototype.ENCODING_ERR was not 5');
    if (!('code' in FileException.prototype))
        log.push('FileException.prototype.code did not exist');
} catch(ex) {
    log.push('Threw: '+ex);
}
log = log.join(', ');
postMessage(log);
/* -->
<!DOCTYPE html>
<title>worker FileError 001 - existance of FilError interface object</title>
<link rel="stylesheet" href="../resources/style.css"/>
<script src="../resources/lib.js"></script>
<script>
onload = function() {
    try {
        var worker = new Worker('#');
        worker.onmessage = function(e) {
            if (e.data == "")
                setResult(1, "FileException members were correct");
            else
                setResult(0, e.data);
        }
    } catch(e) {
        setResult(0, "Threw: " + e);
    }
}
</script>
<body>

</body>
<!-- */ // -->